export const FETCH_PRI_USER_LOG_START = 'FETCH_PRI_USER_LOG_START';
export const FETCH_PRI_USER_LOG_SUCCESS = 'FETCH_PRI_USER_LOG_SUCCESS';
export const FETCH_PRI_USER_LOG_FAIL = 'FETCH_PRI_USER_LOG_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const USER_SWITCH_MODE = 'USER_SWITCH_MODE';
